### ISSUE TITLE
use '/users' instead of '/names' and '/join' instead of '/change'

### ISSUE THREAD

**Issue by karissa** [cabal-club/cabal#17]
'names' could mean 'channel names' , and '/change' could mean 'change nick' so it wasn't very clear to me at first which was wich

**Comment by ralphtheninja** [comment]
+1 for `/join` -1 for `/users` because `/names` is irc lingo.

**Comment by cblgh** [comment]
my only issue with `/join` is the semantics don't match 100% with what irc's join, where you'll join channels and have a list of joined channels from which you'll see updates & mentions

it would be nice to have that in cabal too, but that would mean adding local state and keeping track of joined channels 

(thinking out loud: or do we keep the state in the hyperdb under a user key e.g. `userdata/<user>`, so that you have the same set of joined channels (and other user state) independently of which frontend/client you're using? then again probably not, because you still have a step where you have to identify as someone when you join in the other clients)

anyway im changing to `/join` for now and we'll see how we solve local state stuff :)
