### ISSUE TITLE
colorize names by public key

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal#47]
weechat has a nice feature where names are coloured by hashing a user's name. We could hash each user's public key, which has a nice feature of (statistically) indicating when someone is impersonating someone else by their nick.

I think this really belongs in a common `cabal-client` module that clients use, but putting it here for now.

**Comment by cblgh** [comment]
+1

(btw @noffle you made cabal-client a while back :3
https://github.com/cabal-club/cabal-client)

**Comment by noffle** [comment]
whoops! thanks, I forgot about that

**Comment by nikolaiwarner** [comment]
A feature I'd like to add to cabal-desktop and cabal-mobile would be themeing.... I'm planning on copying slack's implementation of it where they use a string of 8 hex colors as a way to share themes. 

It would be fantastic if that setting could be stored along with other similar user settings on the hyperdb so that any client used by a user would inherit that theme. I'm guessing that would be a feature provided by cabal-node or cabal-client.

My question for cabal cli right now is, if that could be a thing, can the cli utilize a color theme set by the user in a similar way? And, would that translate well at all from desktop to cli?

I can bring this up as a fresh issue if that makes. But I thought I'd mention it since we're talking color.

**Comment by karissa** [comment]
Hey @nikolaiwarner , good idea.

I think it makes sense to have a `~/.cabal` folder with some sort of configuration in there that can be accessed by clients. My suspicion is that clients will interpret and render these options differently and it'll be hard to come up with any abstracted 'global' settings for all clients. 

As far as the original comment, it seems like a good idea although it might be hard to differentiate the colors over time and between different users. I'd probably want to be able to turn this off because I don't really enjoy lots of colors on my screen.

**Comment by nikolaiwarner** [comment]
Yeah! I could see the desktop and mobile sharing themes easily. The cli seems like a different beast.

**Comment by cblgh** [comment]
this is already in
